[package]
name = "zx-spectrum-emulator"
version = "0.1.0"
edition = "2021"
default-run = "zx-spectrum-emulator"

[dependencies]
eframe = { version = "0.35", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11",
] }
egui = "0.35"
rfd = "0.15"
cpal = "0.18"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"

[dev-dependencies]
egui_kittest = "0.35"
