#!/usr/bin/env python3
"""Turn a ROM disassembly into a symbol file the emulator can read.

The disassemblies at https://github.com/ZXSpectrumVault/rom-disassemblies name
every routine in the ROM. They are somebody else's work and are not copied into
this repository; this turns one into the plain list of addresses and names that
AutoDoc reads, which goes in the preferences directory:

    python3 tools/rom-symbols.py Spectrum48.asm > symbols-48.txt

The format they use is a name on its own line, then the label:

    ;; BC-SPACES
    L0030:  PUSH    BC              ; Save number of spaces.

and above that, a heading in capitals saying what the routine is for, which
makes the comment.
"""

import re
import sys

NAME = re.compile(r"^;;\s+(\S+)")
LABEL = re.compile(r"^L([0-9A-Fa-f]{4}):")
HEADING = re.compile(r"^;\s+(THE .*)$")


def symbols(lines):
    """Yield (address, name, comment) for every named routine."""
    heading = ""
    pending = None
    for line in lines:
        line = line.rstrip("\n")

        found = HEADING.match(line)
        if found:
            # "THE 'CREATE BC SPACES' RESTART" -> "the 'create bc spaces' restart"
            heading = found.group(1).strip().rstrip(".")
            continue

        found = NAME.match(line)
        if found:
            pending = found.group(1)
            continue

        found = LABEL.match(line)
        if found and pending:
            address = int(found.group(1), 16)
            name = pending.lower().replace("-", "_").replace("'", "")
            comment = heading[0] + heading[1:].lower() if heading else ""
            yield address, name, comment
            pending = None


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8", errors="replace") as f:
        found = list(symbols(f))

    print(f"# {len(found)} routines, from {sys.argv[1]}")
    print("# Generated by tools/rom-symbols.py from a disassembly at")
    print("# https://github.com/ZXSpectrumVault/rom-disassemblies")
    for address, name, comment in found:
        line = f"{address:04X} {name}"
        if comment:
            line += f" ; {comment}"
        print(line)


if __name__ == "__main__":
    main()
