#!/usr/bin/env python3
"""Turn a ROM disassembly into a symbol file the emulator can read.

The disassemblies at https://github.com/ZXSpectrumVault/rom-disassemblies name
every routine in the ROM. They are somebody else's work and are not copied into
this repository; this turns one into the plain list of addresses and names that
AutoDoc reads, which goes in the preferences directory:

    python3 tools/rom-symbols.py Spectrum48.asm > symbols-48.txt

The format they use is a name on its own line, then the label:

    ;; BC-SPACES
    L0030:  PUSH    BC              ; Save number of spaces.

and above that, a heading in capitals saying what the routine is for, which
makes the comment.
"""

import re
import sys

NAME = re.compile(r"^;;\s+(\S+)")
LABEL = re.compile(r"^L([0-9A-Fa-f]{4}):")
HEADING = re.compile(r"^;\s+(THE .*)$")
# The 128K and +3 ROMs are written up differently: a title between two rules
# of dashes, and then the label a few lines later.
RULE = re.compile(r"^;\s*-{4,}\s*$")
TITLE = re.compile(r"^;\s+(\S.*?)\s*$")
# Both sets name their system variables and entry points with EQU.
EQU = re.compile(r"^(\w+)\s+EQU\s+\$([0-9A-Fa-f]{1,4})", re.IGNORECASE)
# The +3 disassemblies are a third sort again: dZ80 output assembled with
# Z80ASM, so labels are `.lXXXX` and names are `defc NAME=$xxxx`.
DEFC = re.compile(r"^\s*defc\s+(\w+)\s*=\s*\$([0-9A-Fa-f]{1,4})", re.IGNORECASE)
DOT_LABEL = re.compile(r"^\.l([0-9A-Fa-f]{4})\b", re.IGNORECASE)


def slug(text):
    """A name somebody would be willing to type."""
    text = re.sub(r"[^A-Za-z0-9]+", "_", text.strip()).strip("_").lower()
    return re.sub(r"_+", "_", text)[:40] or "routine"


def symbols(lines):
    """Yield (address, name, comment) for every named routine.

    Two conventions are in use across these files. The 48K and ZX81 put the
    name on its own line as `;; NAME`; the 128K and +3 put a title between two
    rules of dashes and the label a few lines below it. Both also name their
    system variables with EQU.
    """
    heading = ""
    pending = None
    banner = None
    in_rule = False
    # A title only names the label that follows it closely. These files open
    # with pages of prose under the same sort of banner as a routine, and
    # without this the first label in the file is called "assembler details".
    since_title = 0
    REACH = 12

    for line in lines:
        line = line.rstrip("\n")
        since_title += 1
        if pending is not None and since_title > REACH:
            pending = None

        found = EQU.match(line) or DEFC.match(line)
        if found:
            # A system variable or entry point named outright.
            yield int(found.group(2), 16), slug(found.group(1)), ""
            continue

        if RULE.match(line):
            # The line between two rules is the title; the second rule closes
            # it and hands it to the next label.
            if banner is not None:
                pending, heading = slug(banner), banner
                banner = None
                since_title = 0
            in_rule = True
            continue

        found = HEADING.match(line)
        if found:
            # "THE 'CREATE BC SPACES' RESTART" -> "the 'create bc spaces' restart"
            heading = found.group(1).strip().rstrip(".")
            in_rule = False
            continue

        found = NAME.match(line)
        if found:
            pending = found.group(1)
            since_title = 0
            in_rule = False
            continue

        if in_rule:
            found = TITLE.match(line)
            if found:
                banner = found.group(1).rstrip(".")
            in_rule = False
            continue

        found = DOT_LABEL.match(line)
        if found and pending:
            yield int(found.group(1), 16), slug(pending), heading
            pending = None
            continue

        found = LABEL.match(line)
        if found and pending:
            address = int(found.group(1), 16)
            name = pending.lower().replace("-", "_").replace("'", "")
            comment = heading[0] + heading[1:].lower() if heading else ""
            yield address, slug(name), comment
            pending = None


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8", errors="replace") as f:
        found = list(symbols(f))

    print(f"# {len(found)} routines, from {sys.argv[1]}")
    print("# Generated by tools/rom-symbols.py from a disassembly at")
    print("# https://github.com/ZXSpectrumVault/rom-disassemblies")
    for address, name, comment in found:
        line = f"{address:04X} {name}"
        if comment:
            line += f" ; {comment}"
        print(line)


if __name__ == "__main__":
    main()
