#!/usr/bin/env python3
"""Turn a SkoolKit disassembly into a symbol file the emulator can read.

Annotated disassemblies of dozens of Spectrum games are kept in the SkoolKit
`.skool` format — https://github.com/mrcook/zx-spectrum-games and the projects
it links to. They are somebody else's work and are not copied into this
repository; this turns one into the list of addresses and names AutoDoc reads:

    python3 tools/skool-symbols.py aticatac.skool > ~/Library/Application\\ Support/ZX\\ Spectrum\\ Emulator/aticatac.symbols.txt

The format is an entry per routine: a comment block saying what it is, an
optional `@label=` giving it a name, then the code.

    ; Move the guardian
    @label=move_guardian
    c$8000 ld a,(hl)

Both halves are used. The label is the name; the comment block is what it does.
A title that says nothing — "Routine at 32768" is what SkoolKit writes when
nobody has described it yet — is dropped rather than repeated back as though it
meant something.
"""

import re
import sys

# `c$8000 ld a,(hl)` — the letter says what the block holds: c code, b bytes,
# t text, w words, g game status buffer, s space, u unused, i ignored.
# SkoolKit takes addresses either way: `$` for hex, bare digits for decimal.
# Four of the games in the collection are written in decimal, and reading them
# as hex quietly finds nothing at all.
ENTRY = re.compile(r"^([cbtgwusi])(\$[0-9A-Fa-f]{1,4}|\d{1,5})\b")
# ` $8001 ld b,$08` — a line within an entry.
WITHIN = re.compile(r"^\s+(\$[0-9A-Fa-f]{1,4}|\d{1,5})\b")
LABEL = re.compile(r"^@label=(\w+)")
COMMENT = re.compile(r"^;\s?(.*)$")
# What SkoolKit writes when there is nothing to say.
UNDESCRIBED = re.compile(
    r"^(routine|data block|game status buffer|message|unused)\b.*\bat\b|^used by\b|^the routine at\b",
    re.I,
)
# SkoolKit's own markup: #R$8000 is a cross-reference to an address, #REGhl a
# register, #N and #FACT and the rest are for the HTML it generates. None of it
# means anything in a plain text file.
MACRO_ADDRESS = re.compile(r"#R\$?([0-9A-Fa-f]{1,4})")
MACRO_REG = re.compile(r"#REG([a-z']+)", re.I)
MACRO_OTHER = re.compile(r"#[A-Z]+(\([^)]*\))?")


def tidy(text):
    """Take SkoolKit's markup out of a comment."""
    text = MACRO_ADDRESS.sub(lambda m: "$" + m.group(1).upper(), text)
    text = MACRO_REG.sub(lambda m: m.group(1).upper(), text)
    text = MACRO_OTHER.sub("", text)
    return re.sub(r"\s+", " ", text).strip()


def symbols(lines):
    """Yield (address, name, comment, kind) for everything named."""
    title = ""
    pending_label = None
    at_entry_start = True

    for line in lines:
        line = line.rstrip("\n")

        found = COMMENT.match(line)
        if found:
            text = found.group(1).strip()
            # The first line of a block comment is the title; the rest is the
            # description, which is often several paragraphs and not wanted.
            if at_entry_start and text:
                title = text
            continue

        found = LABEL.match(line)
        if found:
            pending_label = found.group(1)
            continue

        found = ENTRY.match(line)
        if found:
            kind, address = found.group(1), address_of(found.group(2))
            comment = "" if UNDESCRIBED.match(title) else tidy(title)
            name = pending_label or slug(title) or f"{kind}_{address:04X}"
            yield address, name, comment, kind
            title = ""
            pending_label = None
            at_entry_start = False
            continue

        found = WITHIN.match(line)
        if found and pending_label:
            # A label part-way through a routine: a loop, usually.
            yield address_of(found.group(1)), pending_label, "", "l"
            pending_label = None
            continue

        if not line.strip():
            # A blank line ends an entry, so the next comment is a new title.
            at_entry_start = True


def address_of(text):
    """`$8000` is hex; `32768` is decimal."""
    return int(text[1:], 16) if text.startswith("$") else int(text)


def slug(text):
    text = re.sub(r"[^A-Za-z0-9]+", "_", text.strip()).strip("_").lower()
    return re.sub(r"_+", "_", text)[:40]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8", errors="replace") as f:
        found = list(symbols(f))

    routines = sum(1 for _, _, _, kind in found if kind == "c")
    described = sum(1 for _, _, comment, _ in found if comment)
    print(f"# {len(found)} names from {sys.argv[1]}")
    print(f"# {routines} routines, {described} of them described")
    print("# Generated by tools/skool-symbols.py from a SkoolKit disassembly")
    for address, name, comment, _ in found:
        line = f"{address:04X} {name}"
        if comment:
            line += f" ; {comment}"
        print(line)


if __name__ == "__main__":
    main()
